### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by tanzeelrana** [code-chunks/angular2-logger#166]
`~/Development/quantumex/mobile/s > npm install angular2-logger --save
ionic-hello-world@0.0.0 /home/tanzeelrana/Development/quantumex/mobile/s
├── UNMET PEER DEPENDENCY @angular/common@4.1.1
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.2
├── UNMET PEER DEPENDENCY @angular/core@4.0.2
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.2
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.2
└── angular2-logger@0.5.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/common@4.1.1 requires a peer of @angular/core@4.1.1 but none was installed.
npm WARN @angular/forms@4.0.2 requires a peer of @angular/common@4.0.2 but none was installed.
npm WARN @angular/platform-browser@4.0.2 requires a peer of @angular/common@4.0.2 but none was installed.
npm WARN @angular/platform-browser-dynamic@4.0.2 requires a peer of @angular/common@4.0.2 but none was installed.
npm WARN angular2-logger@0.5.1 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-logger@0.5.1 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN angular2-logger@0.5.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-logger@0.5.1 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN angular2-logger@0.5.1 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/common@4.0.2 but none was installed.
`

![image](https://cloud.githubusercontent.com/assets/2520028/25831706/ed4e48c6-3433-11e7-98cd-4c18887d4144.png)

My package.json file : 
`{
  "name": "ionic-hello-world",
  "version": "0.0.0",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "^4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/geolocation": "^3.6.1",
    "@ionic-native/splash-screen": "3.6.1",
    "@ionic-native/status-bar": "3.6.1",
    "@ionic/storage": "2.0.1",
    "@types/leaflet": "^1.0.60",
    "angular2-logger": "^0.5.1",
    "aws-sdk": "^2.49.0",
    "cordova-android": "^6.2.3",
    "cordova-plugin-compat": "^1.1.0",
    "cordova-plugin-console": "1.0.5",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "2.2.2",
    "cordova-plugin-whitelist": "1.3.1",
    "ionic-angular": "3.1.1",
    "ionic-plugin-keyboard": "~2.2.1",
    "ionicons": "3.0.0",
    "leaflet": "^1.0.3",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@types/node": "^7.0.18",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-splashscreen"
  ],
  "cordovaPlatforms": [],
  "description": "s: An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-geolocation": {}
    },
    "platforms": [
      "android"
    ]
  }
}
`

**Comment by langley-agm** [comment]
Tracked by #165.
