### ISSUE TITLE
is any difference with console.log/warn/error?

### ISSUE THREAD

**Issue by dyh333** [code-chunks/angular2-logger#167]
hi, @langley-agm , is this repo  any difference with console.log/warn/error?  i don't understand in what case should I use this repo

**Comment by langley-agm** [comment]
Hello @dyh333 , 

The most simple/basic use case is so you can see all the logging while working in development and turn it off for production.

One more common test case is to leave it showing only warning and errors, and when you want to debug or understand more in deep what's happening in the app, you turn info or debug mode on so you can see more info, and once you've found what you're looking for, to turn it back off.

**Comment by dyh333** [comment]
yeah, thanks your reply
