### ISSUE TITLE
Angular 5 should be listed as a valid peer dependency

### ISSUE THREAD

**Issue by mdentremont** [code-chunks/angular2-logger#176]
I am using Angular 5 and it appears to work fine with angular2-logger, but unfortunately your package.json doesn't list Angular 5 as being supported, so I get a bunch of warning when running npm commands:

npm WARN angular2-logger@0.6.0 requires a peer of @angular/common@^4.0.2 but none was installed.                   
npm WARN angular2-logger@0.6.0 requires a peer of @angular/compiler@^4.0.2 but none was installed.                 
npm WARN angular2-logger@0.6.0 requires a peer of @angular/core@^4.0.2 but none was installed.                     
npm WARN angular2-logger@0.6.0 requires a peer of @angular/platform-browser@^4.0.2 but none was installed.         
npm WARN angular2-logger@0.6.0 requires a peer of @angular/platform-browser-dynamic@^4.0.2 but none was installed. 

Having 5+ listed in the peer dependencies would be amazing!

**Comment by langley-agm** [comment]
Should be a fairly easy change, good opportunity for new contributors, if none offers a PR soon, I'll make the change within a couple of weeks.

**Comment by mdentremont** [comment]
@langley-agm done 👍 https://github.com/code-chunks/angular2-logger/pull/177
