### ISSUE TITLE
@angular migration needed

### ISSUE THREAD

**Issue by Supamiu** [code-chunks/angular2-logger#33]
Source:
https://github.com/angular/angular/blob/master/CHANGELOG.md

A lot of things changed in angular-2.0.0-rc.0 and we need them in angular2-logger asap to avoid dependency conflicts, I cloned the repo to do it by myself and issue a pull request, but if you can do it by yourself, I'm sure it'll be better/faster :+1:

**Comment by langley-agm** [comment]
Hello @Supamiu 

Once again, thanks for the help! I saw the changes in the quickstart in the main page, whoever the npm repo is still pointing to [beta.17](https://www.npmjs.com/package/angular2) and if you run `npm i angular2` you still get the beta.17, which doesn't have these changes yet. 

More than likely they're getting ready for the [ng-conf](https://www.ng-conf.org/#/) tomorrow. As soon as all sources get updated I'll apply your changes.

**Comment by Supamiu** [comment]
```npm i angular2``` will always be pointing to beta.17, angular rc0 is now @angular, you can't install angular2 by just doing npm i angular2 now. 

see [rc0 changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02) for more informations

**Comment by langley-agm** [comment]
You are right, now we have to use `npm i --save @angular/core ...`. 

I see that you fixed your pull request but you made a merge without a rebase, I'm trying to keep the history clean of merges so I'm going to try to fork somehow your pull request to fix that before accepting it if that's ok with you.
