### ISSUE TITLE
Wrong assignment with typescript compilation?

### ISSUE THREAD

**Issue by Mc128k** [code-chunks/angular2-logger#61]
Hi, it seems that when compiling the files the assignment from the enum object to an internal variable is wrong:

```
[default] /home/mc128k/node/etiquette-client/node_modules/angular2-logger/app/core/logger.ts:59:39
    Type 'string' is not assignable to type 'Level'.
```

Might be a config issue, but it should make sense, the code here assigns a string to a Level:

```
    private _loadLevel = (): Level => localStorage.getItem( this._storeAs );
```

**Comment by langley-agm** [comment]
Hi @Mc128k, there's another issue already open for this, so I'm closing it.
In order to avoid this use an officially released version of Typescript like 1.8,

See #39
