### ISSUE TITLE
[Question] Using with webpack

### ISSUE THREAD

**Issue by rbasniak** [code-chunks/angular2-logger#72]
Hi, the quickstart covers the setup when using SystemJS to load Angular2. Is it possible to use it when using Webpack instead?

**Comment by rbasniak** [comment]
Hi, the quickstart covers the setup when using SystemJS to load Angular2. Is it possible to use it when using Webpack instead?

**Comment by langley-agm** [comment]
See: https://angular.io/docs/ts/latest/guide/webpack.html

Just add `import 'angular2-logger';` to the vendor.ts file.
