### ISSUE TITLE
Compatible warning?

### ISSUE THREAD

**Issue by jaandric** [code-chunks/angular2-logger#76]
While installing angular2-logger i get this WARN-s:

npm WARN angular2-logger@0.5.0 requires a peer of @angular/common@2.0.0 but none was installed.                                                                                           
npm WARN angular2-logger@0.5.0 requires a peer of @angular/compiler@2.0.0 but none was installed.                                                                                         
npm WARN angular2-logger@0.5.0 requires a peer of @angular/core@2.0.0 but none was installed.                                                                                             
npm WARN angular2-logger@0.5.0 requires a peer of @angular/platform-browser@2.0.0 but none was installed. 

Im using:             
        "@angular/common": "~2.1.0",
        "@angular/compiler": "~2.1.0",
        "@angular/core": "~2.1.0",
        "@angular/platform-browser": "~2.1.0",

After installing logger actually works!

**Comment by langley-agm** [comment]
I think this is related to #74 . I'll merge it soon.
I was hoping greenkeeper would catch it but for some reason it isn't.
