### ISSUE TITLE
Feature: add an observable

### ISSUE THREAD

**Issue by no-more** [code-chunks/angular2-logger#92]
Hi,

Do you think it could be possible to add an observable which could be subscribed in order to retrieve and use all logging events in another component?
Of course no need to store an history of the events, just emit on the observable each time a new log request occurs.

Thanks a lot.

**Comment by langley-agm** [comment]
Hi @no-more ,

I can't say it hasn't cross my mind but could you elaborate some about the business requirement for this? What would you do with this?

**Comment by langley-agm** [comment]
Closing for now, if new info gets added it'll be reconsidered for re opening.

**Comment by no-more** [comment]
Hi,

I'm very sorry I completely missed your response and forgot about this. I have implemented a service over this logger in order to provide this feature. But I still think it's very useful if it's included directly into this component.

In my case I mainly use the observable to display some information on the screen (for example or errors). I have a component dedicated to this which listen to logs change and decide if something needs to be displayed or not. In all my application I only have to use the logger service.

Thanks a lot
And Happy new Year!

**Comment by langley-agm** [comment]
Hi @no-more,

Happy New Year !

I'm not so sure about this. The way I see it, the messages for the logger aren't meant to be messages for the end user but for the developers to help with troubleshooting, let's see if more people request this feature in the future.

**Comment by bushev** [comment]
Hello @langley-agm !

I'm trying to figure out, how to subscribe to log event. I want to push error logs from app to the server. Is it possible?

**Comment by langley-agm** [comment]
Hi @bushev , not natively by the app, but you can create your custom logger, which is a good practice anyway in case you switch implementations later on, and wrap this logger into your custom one to do what you want, then call this logger.
