### ISSUE TITLE
[Feature] Show 'real' invocation place

### ISSUE THREAD

**Issue by mp3por** [code-chunks/angular2-logger#95]
I would like to see in console the 'real' invocation place of the log msg rather than 'logger.ts:76'

**Comment by langley-agm** [comment]
I don't think this is possible is it?

**Comment by mp3por** [comment]
Not sure ... can do some research but it won't be till the end of the week :( However I have seen it working sooo it should be doable somehow.

NOTE: You can hijack the console function, however I  will have to test if this will work as expected :)

**Comment by langley-agm** [comment]
> However I have seen it working 

Where?

**Comment by mp3por** [comment]
I will try to find it ... ;)

**Comment by langley-agm** [comment]
Closing for now, if new info gets added it'll be reconsidered for re opening.
